// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_provenance
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2022-03-21, STEPS: `[50, ]`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 128

// Executed Command:
// ./borlaug
// benchmark
// --dev
// --pallet
// pallet_provenance
// --extrinsic
// *
// --steps=50
// --repeat=5
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./weights/provenance/weights.rs
// --template=./frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_provenance.
pub trait WeightInfo {
    fn create_registry(a: u32) -> Weight;
    fn update_registry(a: u32) -> Weight;
    fn remove_registry() -> Weight;
    fn create_definition(a: u32, b: u32, c: u32) -> Weight;
    fn set_definition_active() -> Weight;
    fn set_definition_inactive() -> Weight;
    fn remove_definition(a: u32) -> Weight;
    fn update_definition_step() -> Weight;
    fn create_process(a: u32) -> Weight;
    fn update_process(a: u32) -> Weight;
    fn remove_process(a: u32) -> Weight;
    fn add_child_definition() -> Weight;
    fn remove_child_definition() -> Weight;
    fn attest_process_step(a: u32, b: u32, c: u32) -> Weight;
    fn complete_process(a: u32) -> Weight;
}

/// Weights for pallet_provenance using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn create_registry(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn update_registry(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn remove_registry() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn create_definition(_a: u32, _b: u32, _c: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn set_definition_active() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn set_definition_inactive() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn remove_definition(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn update_definition_step() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn create_process(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn update_process(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn remove_process(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn add_child_definition() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn remove_child_definition() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn attest_process_step(_a: u32, _b: u32, _c: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn complete_process(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn create_registry(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn update_registry(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn remove_registry() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn create_definition(_a: u32, _b: u32, _c: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn set_definition_active() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn set_definition_inactive() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn remove_definition(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn update_definition_step() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn create_process(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn update_process(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn remove_process(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn add_child_definition() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn remove_child_definition() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn attest_process_step(_a: u32, _b: u32, _c: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn complete_process(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
}
