[package]
authors = ["Borlaug"]
build = "build.rs"
edition = "2018"
name = "Borlaug"
version = "0.0.1"

[profile.release]
panic = "unwind"

[[bin]]
name = "borlaug"
path = "src/main.rs"

[dependencies]
# third-party dependencies
codec = {package = "parity-scale-codec", version = "2.0.0"}
futures = {version = "0.3.9", features = ["compat"]}
hex-literal = "0.3.1"
jsonrpc-core = "15.0"
jsonrpc-core-client = "15.0"
jsonrpc-derive = "15.0"
log = "0.4.11"
pallet-transaction-payment-rpc = "3.0.0"
parking_lot = "0.10.0"
serde = {version = "1.0.102", features = ["derive"]}

# primitives
sp-authority-discovery = "3.0.0"

# client dependencies
chrono = {version = "0.4.9", features = ["serde"]}
grandpa = {version = "0.9.0", package = "sc-finality-grandpa"}
sc-authority-discovery = "0.9.0"
sc-basic-authorship = "0.9.0"
sc-chain-spec = "3.0.0"
sc-cli = "0.9.0"
sc-client-api = "3.0.0"
sc-consensus = "0.9.0"
sc-consensus-babe = {version = "0.9.0", optional = true}
sc-consensus-babe-rpc = {version = "0.9.0", optional = true}
sc-consensus-epochs = "0.9.0"
sc-consensus-manual-seal = {version = "0.9.0", optional = true}
sc-consensus-slots = "0.9.0"
sc-executor = "0.9.0"
sc-finality-grandpa-rpc = {version = "0.9.0", optional = true}
sc-keystore = "3.0.0"
sc-network = "0.9.0"
sc-rpc = "3.0.0"
sc-rpc-api = "0.9.0"
sc-service = "0.9.0"
sc-sync-state-rpc = "0.9.0"
sc-telemetry = "3.0.0"
sc-transaction-pool = "3.0.0"
serde_json = "1.0.41"
sp-api = "3.0.0"
sp-block-builder = "3.0.0"
sp-blockchain = "3.0.0"
sp-consensus = "0.9.0"
sp-consensus-babe = {version = "0.9.0", optional = true}
sp-core = "3.0.0"
sp-finality-grandpa = {version = "3.0.0", optional = true}
sp-inherents = "3.0.0"
sp-keystore = "0.9.0"
sp-runtime = "3.0.0"
sp-timestamp = {version = "3.0.0", optional = true}
sp-transaction-pool = "3.0.0"
structopt = "0.3.17"
substrate-frame-rpc-system = "3.0.0"

# frame dependencies
pallet-im-online = {version = "3.0.0", default-features = false}

# These dependencies are used for runtime benchmarking
frame-benchmarking = "3.0.0"
frame-benchmarking-cli = "3.0.0"

runtime = {package = "borlaug-runtime", path = "runtime", optional = true}

groups-runtime-api = {path = "pallets/groups-runtime-api"}
provenance-runtime-api = {path = "pallets/provenance-runtime-api"}

pallet-primitives = {path = "pallets/primitives", default-features = false}

[build-dependencies]
substrate-build-script-utils = "3.0.0"
vergen = "3.0.4"

[workspace]
exclude = ["runtime/wasm"]
members = ["runtime", "pallets/*"]

[features]
default = []
# use grandpa / babe consensus (chain must not be stopped)
grandpa_babe = [
  "sp-consensus-babe",
  "sp-finality-grandpa",
  "sc-consensus-babe-rpc",
  "sc-consensus-babe",
  "sc-finality-grandpa-rpc",
  "runtime/grandpa_babe",
]
# use instant seal consensus - useful for development, but not to be used in production
instant_seal = [
  "sc-consensus-manual-seal",
  "sp-timestamp",
  "runtime/instant_seal",
]
