[package]
name = "Borlaug"
version = "0.0.1"
authors = ["Borlaug Web Services"]
description = "Blockchain for self organizing communities"
build = "build.rs"
edition = "2018"

[profile.release]
panic = "unwind"

[[bin]]
name = "borlaug"
path = "src/main.rs"

[dependencies]
hex-literal = "0.2.1"
serde_json = "1.0.41"
futures = "0.3.1"
futures01 = { package = "futures", version = "0.1.29" }
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.2.0" }
trie-root = "0.15.2"
jsonrpc-core = "14.0.3"

sp-io = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b'}
sc-cli = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sp-core = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sc-executor = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sc-service = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sc-network = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sp-consensus = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
grandpa = { package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
grandpa-primitives = { package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sc-client = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sc-client-api = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b' }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b'}

structopt = "0.3.8"

runtime = { package = "borlaug-runtime", path = "runtime" }

[build-dependencies]
vergen = "3.0.4"
build-script-utils = { package = "substrate-build-script-utils", version = "2.0.0-alpha.5" }

[workspace]
members = [
	"runtime",
	"pallets/*"
]
exclude = [ "runtime/wasm" ]