[package]
name = "Borlaug"
version = "0.0.1"
authors = ["Borlaug"]
build = "build.rs"
edition = "2018"

[profile.release]
panic = "unwind"

[[bin]]
name = "borlaug"
path = "src/main.rs"

[dependencies]
hex-literal = "0.2.1"
serde_json = "1.0.41"
futures = "0.3.1"
futures01 = { package = "futures", version = "0.1.29" }
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.2.0" }
trie-root = "0.15.2"
jsonrpc-core = "14.0.3"

sp-io = "2.0.0-alpha.5"
sc-cli = "0.8.0-alpha.5"
sp-core = "2.0.0-alpha.5"
sc-executor = "0.8.0-alpha.5"
sc-service = "0.8.0-alpha.5"
sp-inherents = "2.0.0-alpha.5"
sc-transaction-pool = "2.0.0-alpha.5"
sp-transaction-pool = "2.0.0-alpha.5"
sc-network = "0.8.0-alpha.5"
sc-consensus-aura = "0.8.0-alpha.5"
sp-consensus-aura = "0.8.0-alpha.5"
sp-consensus = "0.8.0-alpha.5"
grandpa = { package = "sc-finality-grandpa", version = "0.8.0-alpha.5" }
grandpa-primitives = { package = "sp-finality-grandpa", version = "2.0.0-alpha.5" }
sc-client = "0.8.0-alpha.5"
sc-client-api = "2.0.0-alpha.5"
sp-runtime = "2.0.0-alpha.5"
sc-basic-authorship = "0.8.0-alpha.5"

structopt = "0.3.8"

runtime = { package = "borlaug-runtime", path = "runtime" }

[build-dependencies]
vergen = "3.0.4"
build-script-utils = { package = "substrate-build-script-utils", version = "2.0.0-alpha.5" }

[workspace]
members = [
	"runtime",
	"pallets/*"
]
exclude = [ "runtime/wasm" ]