[package]
name = "Borlaug"
version = "0.0.1"
authors = ["Borlaug"]
build = "build.rs"
edition = "2018"

[profile.release]
panic = "unwind"

[[bin]]
name = "borlaug"
path = "src/main.rs"

[dependencies]
serde_json = "1.0.41"
futures = "0.3.5"
log = "0.4.11"
parking_lot = "0.10.0"
structopt = "0.3.17"
jsonrpc-core = "15.0.0"

sp-block-builder = "2.0.1"
sc-rpc = "2.0.1"
sp-api = "2.0.1"
sc-rpc-api = "0.8.1"
sp-blockchain = "2.0.1"
substrate-frame-rpc-system = "2.0.1"
pallet-transaction-payment-rpc = "2.0.1"
sc-cli = "0.8.1"
sp-core = "2.0.1"
sc-executor = "0.8.1"
sc-service = "0.8.1"
sp-inherents = "2.0.1"
sc-transaction-pool = "2.0.1"
sp-transaction-pool = "2.0.1"
sc-network = "0.8.1"
sc-consensus-aura = "0.8.1"
sp-consensus-aura = "0.8.1"
sp-consensus = "0.8.1"
sc-consensus = "0.8.1"
sc-finality-grandpa = "0.8.1"
sp-finality-grandpa = "2.0.1"
sc-client-api = "2.0.1"
sp-runtime = "2.0.1"
sc-basic-authorship = "0.8.1"

# These dependencies are used for runtime benchmarking
frame-benchmarking = "2.0.1"
frame-benchmarking-cli = "2.0.1"

runtime = { package = "borlaug-runtime", path = "runtime" }

[build-dependencies]
vergen = "3.0.4"
substrate-build-script-utils = "2.0.1"

[workspace]
members = ["runtime", "pallets/*"]
exclude = ["runtime/wasm"]
