// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_audits
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 3.0.0
//! DATE: 2022-03-21, STEPS: `[50, ]`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 128

// Executed Command:
// ./borlaug
// benchmark
// --dev
// --pallet
// pallet_audits
// --extrinsic
// *
// --steps=50
// --repeat=5
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./weights/audits/weights.rs
// --template=./frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{
    traits::Get,
    weights::{constants::RocksDbWeight, Weight},
};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_audits.
pub trait WeightInfo {
    fn create_audit() -> Weight;
    fn delete_audit() -> Weight;
    fn link_audit() -> Weight;
    fn unlink_audit() -> Weight;
    fn accept_audit() -> Weight;
    fn assign_auditors_initial_assign() -> Weight;
    fn assign_auditors_replace() -> Weight;
    fn reject_audit() -> Weight;
    fn complete_audit() -> Weight;
    fn create_observation() -> Weight;
    fn create_evidence(_a: u32, _b: u32, _c: u32, _d: u32) -> Weight;
    fn link_evidence() -> Weight;
    fn unlink_evidence() -> Weight;
    fn delete_evidence(a: u32) -> Weight;
}

/// Weights for pallet_audits using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    fn create_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn delete_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn link_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn unlink_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn accept_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn assign_auditors_initial_assign() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn assign_auditors_replace() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn reject_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn complete_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn create_observation() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn create_evidence(_a: u32, _b: u32, _c: u32, _d: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn link_evidence() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn unlink_evidence() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn delete_evidence(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn create_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn delete_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn link_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn unlink_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn accept_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn assign_auditors_initial_assign() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn assign_auditors_replace() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn reject_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn complete_audit() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn create_observation() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn create_evidence(_a: u32, _b: u32, _c: u32, _d: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
    fn link_evidence() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn unlink_evidence() -> Weight {
        Weight::from_parts(0, 0)
    }
    fn delete_evidence(_a: u32) -> Weight {
        Weight::from_parts(0, 0)
    }
}
