[package]
authors = ['Borlaug Blockchain']
edition = '2018'
name = 'borlaug-runtime'
version = '2.0.0'

[dependencies]
# third-party dependencies
serde = { version = "1.0.101", optional = true, features = ["derive"] }
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false, features = ["derive"] }


# primitives
sp-std = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
sp-version = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
sp-session = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
sp-offchain = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
sp-api = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }

system = { package = "frame-system", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
frame-executive = { git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
system-rpc-runtime-api = { package = "frame-system-rpc-runtime-api", git = "https://github.com/paritytech/substrate", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
balances = { package = "pallet-balances", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
aura = { package = "pallet-aura", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
grandpa = { package = "pallet-grandpa", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
indices = { package = "pallet-indices", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
randomness-collective-flip = { package = "pallet-randomness-collective-flip", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
timestamp = { package = "pallet-timestamp", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
sudo = { package = "pallet-sudo", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
transaction-payment = { package = "pallet-transaction-payment", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
transaction-payment-rpc-runtime-api = { package = "pallet-transaction-payment-rpc-runtime-api",  git = "https://github.com/paritytech/substrate", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
collective = { package = "pallet-collective", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }
membership = { package = "pallet-membership", git = "https://github.com/paritytech/substrate.git", rev = '67f354f57e738fa575775f7fa0fb903e8972182b', default-features = false }

# Borlaug Dependencies
identity = { package = "pallet-identity", path = "../pallets/identity", default-features = false }
asset-registry = { package = "pallet-asset-registry", path = "../pallets/asset-registry", default-features = false }
audits = { package = "pallet-audits", path = "../pallets/audits", default-features = false }

[build-dependencies]
wasm-builder-runner = { package = "substrate-wasm-builder-runner", version = "1.0.5" }

[features]
default = ["std"]
no_std = []
std = [
	"codec/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-version/std",
	"serde",
	"sp-offchain/std",
	"sp-session/std",
	"sp-transaction-pool/std",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-inherents/std",
	"sp-consensus-aura/std",
	"system/std",
	"frame-support/std",
	"frame-executive/std",
	"balances/std",
	"aura/std",
	"grandpa/std",
	# "indices/std",
	"collective/std",
	"membership/std",
	"timestamp/std",
	"sudo/std",
	"transaction-payment/std",
	"randomness-collective-flip/std",
	"transaction-payment-rpc-runtime-api/std",
	"system-rpc-runtime-api/std",
	"identity/std",
	"asset-registry/std",
	"audits/std",
]