[package]
authors = ["Borlaug Blockchain"]
description = "A trait that supplies group information for groups of accounts for use in a Substrate runtime"
edition = "2021"
name = "group-info"
version = "0.1.0"

[features]
default = ['std']
std = []

[dependencies]
# Substrate packages
