[package]
name = "pallet-provenance"
version = "0.1.0"
authors = ["Borlaug Blockchain"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false }

sp-runtime = { version = "2.0.0-rc4", default-features = false }
sp-core = { version = "2.0.0-rc4", default-features = false }
sp-io = { version = "2.0.0-rc4", default-features = false }
sp-std = { package = "sp-std", version = "2.0.0-rc4", default-features = false }
randomness = { package = "pallet-randomness-collective-flip", version = "2.0.0-rc4", default-features = false }
balances = { package = "pallet-balances", version = "2.0.0-rc4", default-features = false }
timestamp = { package = "pallet-timestamp", version = "2.0.0-rc4", default-features = false }

frame-system = { version = "2.0.0-rc4", default-features = false }
frame-support = { version = "2.0.0-rc4", default-features = false }

primitives = { package = "pallet-primitives", path = "../primitives", default-features = false }

[dev-dependencies]
lazy_static = "1.4.0"
parking_lot = "0.10.0"
chrono = "0.4"

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    "sp-io/std",
    "sp-std/std",
    "balances/std",
    "frame-support/std",
    'frame-system/std',
    'sp-runtime/std',
    'randomness/std',
    "timestamp/std",
    "primitives/std",
]
