build.incremental = false

[alias]
# Run commands as CI does
ci-check = "check --all --all-targets --all-features"
ci-clippy = "clippy --all --all-targets --features 'grandpa_aura runtime-benchmarks' -- -Dwarnings -Drust-2018-idioms -Adeprecated -Atype_complexity -Atabs_in_doc_comments"
ci-fmt = "fmt --all -- --check"

# Format Rust code with stable-compatible nightly features
fmt-unstable = "fmt --all -- --config-path rustfmt-unstable.toml"

# [target.x86_64-unknown-linux-gnu]
# linker = "/usr/bin/clang"
# rustflags = ["-Clink-arg=-fuse-ld=lld", "-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
linker = "lld-link.exe"
