[package]
name = "pallet-primitives"
version = "0.1.0"
authors = ["Borlaug Blockchain"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
codec = { package = "parity-scale-codec", version = "1.3.4", default-features = false }

sp-runtime = { version = "2.0.0-rc5", default-features = false }
sp-core = { version = "2.0.0-rc5", default-features = false }
sp-std = { package = "sp-std", version = "2.0.0-rc5", default-features = false }

timestamp = { package = "pallet-timestamp", version = "2.0.0-rc5", default-features = false }

frame-system = { version = "2.0.0-rc5", default-features = false }
frame-support = { version = "2.0.0-rc5", default-features = false }


[features]
default = ['std']
no_std = []
std = [
    'serde',
    'codec/std',
    'sp-runtime/std',
    "sp-core/std",
    "sp-std/std",
    "timestamp/std",
    'frame-system/std',
    'frame-support/std',
]
