[package]
name = "pallet-primitives"
version = "0.1.0"
authors = ["Borlaug Blockchain"]
edition = "2018"

[dependencies]
serde = { version = "1.0", optional = true }
codec = { package = "parity-scale-codec", version = "1.2.0", default-features = false }

sp-runtime = { git = "https://github.com/paritytech/substrate.git", rev = 'd1b9ccad107e4899978858de5ddd2868b9777aab', default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git", rev = 'd1b9ccad107e4899978858de5ddd2868b9777aab', default-features = false }
sp-std = { package = "sp-std", git = "https://github.com/paritytech/substrate.git", rev = 'd1b9ccad107e4899978858de5ddd2868b9777aab', default-features = false }

timestamp = { package = "pallet-timestamp", git = "https://github.com/paritytech/substrate.git", rev = 'd1b9ccad107e4899978858de5ddd2868b9777aab', default-features = false }

frame-system = { git = "https://github.com/paritytech/substrate.git", rev = 'd1b9ccad107e4899978858de5ddd2868b9777aab', default-features = false }
frame-support = { git = "https://github.com/paritytech/substrate.git", rev = 'd1b9ccad107e4899978858de5ddd2868b9777aab', default-features = false }


[features]
default = ['std']
no_std = []
std = [
    'serde',
    'codec/std',    
    'sp-runtime/std',
    "sp-core/std",
    "sp-std/std",
    "timestamp/std",
    'frame-system/std',    
	'frame-support/std'
	
]